name: blindover_flutter
description: Classify materials for blind individuals
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  camera: ^0.10.5
  flutter:
    sdk: flutter
  lottie: ^2.4.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/camera.json
