name: blindover_flutter
description: Classify materials for blind individuals
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  dio: ^5.1.2
  lottie: ^2.4.0
  permission_handler: ^10.2.0
  path_provider: ^2.0.15
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/camera.json
